big update
willnode/autobloom pull request #16
Opened 2023-04-08 21:41 UTC by aritz331

2023-04-08 21:43 UTC, aritz331 commented
idk why i forked it to the organization lol

2023-04-08 22:19 UTC, aritz331 commented on src/run.bat
windows terminal minimizing problem fix (by using good ol' conhost - the classic command line window manager)

2023-04-08 22:21 UTC, aritz331 commented on src/run.bat
even if they fix it i wouldnt recommend removing it, because some people might have the version with the problem and apart from that it doesnt really affect anything

2023-04-09 02:01 UTC, willnode commented
Thank you for this! I'll take time to test this on my machine before being merged. Let me know when it's ready.

2023-04-09 05:13 UTC, askfriends commented
Thanks you for the update, but kindly consider these important changes if u can include them.
1. Add dark theme support
2. The bloom should run in reverse order when logging off or shutting down pc.
3. Add more wallpapers like this.

2023-04-09 08:45 UTC, aritz331 commented
@askfriends
1. we cannot add dark theme because the animation was made by microsoft and they didnt make the dark theme version afaik
2. we cannot know when the computer shuts down or stop the shutdown before playing the animation
3. we would need to find all the animations and its not an easy process

2023-04-09 08:54 UTC, aritz331 commented
@willnode ok, i tested it but i had to change some things. also, do you want me to implement the vbs method of hiding the window? it hides the window before it appears, unlike with the powershell one

2023-04-09 14:48 UTC, aritz331 commented
yeah i think its better to implement the vbs method because its ugly to see a console window on startup

2023-04-09 17:13 UTC, aritz331 commented
@willnode you can merge now, i added the vbs hiding method and its way better
i also updated the readme.md with a new demonstration video

2023-04-09 18:38 UTC, aritz331 commented
wait, theres a dark version of the animation! i will implment it on a separate pr after this one is merged

2023-04-09 23:34 UTC, willnode requested changes

2023-04-09 23:34 UTC, willnode commented on install.bat
>  cls
```suggestion
powershell -Command "Set-ExecutionPolicy -Scope CurrentUser -ExecutionPolicy RemoteSigned"
cls
```

By default PowerShell scripts are disabled.

2023-04-10 01:03 UTC, willnode approved these changes

2023-04-10 01:05 UTC, merged

2023-04-10 01:07 UTC, aritz331 commented
could you make a new release please?

2023-04-10 01:15 UTC, willnode commented
Will do it in a few moments 👍

2023-04-10 01:16 UTC, aritz331 commented
k nice

2023-04-10 01:17 UTC, aritz331 commented
dont forget to excmude the .git folder

2023-04-10 09:09 UTC, aritz331 commented
new release wen

2023-04-18 17:45 UTC, aritz331 commented
hi @willnode i was about to implement dark mode but the mpv window appears on top of the taskbar (dark mode only), do you know how to fix it? (check [my repo](/aritz331/autobloom) for the updated version w/ dark mode)